version: 1
update_configs:
  - package_manager: "submodules"
    directory: "/"
    update_schedule: "daily"
    commit_message:
      prefix: "[dependabot] "
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
